### ISSUE TITLE
Update for `bs-platform 5.0.0-dev.5`

### ISSUE THREAD

**Issue by justgage** [darklang/tablecloth#1]
You can install it like:
```
npm i --save-dev bs-platform@next
```

Main one is:
```
[start-reason]   deprecated: Js.Re.test
[start-reason] Please use Js.Re.test_ instead
```

There might be others

https://twitter.com/bobzhang1988/status/1107099244748394497

Changes: https://github.com/BuckleScript/bucklescript/blob/master/Changes.md#500

**Comment by pbiggar** [comment]
Thanks for the suggestion!

If the functions have changed names, supporting both older versions of bs-platform and new versions might be awkward. What do you think we should do there?

**Comment by justgage** [comment]
Sorry, yeah I realize now that this would not be possible to do till `bsb` is the released. I think it's good the way it is for now.

**Comment by jdeisenberg** [comment]
The fix appears to be to rename the function and reverse the order of the arguments;
```
let contains ~(re : Js.Re.t) (s : string) : bool = Js.Re.test s re
```
becomes:
```
let contains ~(re : Js.Re.t) (s : string) : bool = Js.Re.test_ re s
```
Similarly,  you need to fix the call to `exec`:

```
  let matches ~(re : Js.Re.t) (s : string) : Js.Re.result option =
    Js.Re.exec_ re s
```
This is in file `bs/src/tablecloth.ml` around line 800.

**Comment by pbiggar** [comment]
@jdeisenberg Any idea how we would handle keeping the library working in both versions of bs-platform?

**Comment by jdeisenberg** [comment]
I don't see any regular expression stuff in `native/src/tablecloth.ml` yet. Is there a native OCaml regular expression library that everyone uses?

**Comment by pbiggar** [comment]
There's re2, which has the benefit of being fairly modern and I think has similar syntax to what the JS side uses.

There's also Str, which is a big nasty.

I forgot that I didn't do regex on the native stuff. I found it hard to make a good interface that worked for both. So one option is to try to figure out a nice interface that works for both, and another option is to remove it from the bs side until we figure one out.

**Comment by bkase** [comment]
With the new bs-platform, tablecloth fails to build because of this deprecation: The temporary workaround is adding a `-3` if anyone else runs into this.

```
-  "bsc-flags": ["-bs-g", "-bs-super-errors", "-warn-error", "@A", "-w", "-4-9-30-40-41-42-102"],
+  "bsc-flags": [
+    "-bs-g",
+    "-bs-super-errors",
+    "-warn-error",
+    "@A",
+    "-w",
+    "-4-9-30-40-41-42-102-3"
+  ],
```

**Comment by pbiggar** [comment]
I'm not sure how to wrap both releases, but given it doesn't have support in the native version, let's just remove the Regex module. Would be happy to take a PR doing that.

**Comment by joprice** [comment]
@pbiggar I know it's a moot point since you hadn't provided a native version, but if you needed to target different versions, bucklescript does support conditional compilation and it seems that both bs and ocaml versions are available https://bucklescript.github.io/docs/en/conditional-compilation.
