### ISSUE TITLE
Specific issues to contribute to

### ISSUE THREAD

**Issue by dylanirlbeck** [darklang/tablecloth#106]
Hi all! So I'm a college student who loves Reason/OCaml, and also have my college's [annual Hackathon](https://www.hackillinois.org/) next weekend. What's cool about the University of Illinois' Hackathon is that it's fully open-source; this got me thinking, what better project to do then to contribute to a standard library!

If one of the maintainers could post several issues (new algorithms/methods, documentation fixes, etc.) they think I could tackle in a 36 hour period, that'd be awesome! If there are enough doable things I can contribute to, I definitely have a shot at winning 😄 

Thanks in advance!

**Comment by garyrob** [comment]
I'm not a maintainer, but last time I looked I didn't notice file I/O in Tablecloth, and that's something I'd need in order to start using it!

**Comment by pbiggar** [comment]
Apologies for the delay in responding. Planning to be more responsive to issues like this in the future.

**Comment by Dean177** [comment]
For anyone else that comes across this issue there are now a couple of good issues to get started with the codebase:
- https://github.com/darklang/tablecloth/issues/140
- https://github.com/darklang/tablecloth/issues/139
- https://github.com/darklang/tablecloth/issues/138

And I will be trying to proactively tag things with 'help wanted' and 'good first issue'.

Also don't hesitate to reach out and ask questions via issues / discord / twitter.
