### ISSUE TITLE
Result.map inconsistent with Option.map

### ISSUE THREAD

**Issue by joefiorini** [darklang/tablecloth#114]
Option.map uses a labelled parameter for the function and therefore can be called either subject first or subject last (meaning it is interchangeable with `->` and `|>`). However, `Result.map` does not use a labelled parameter for the function meaning it can only be called subject-last, meaning it only works with `|>`. Is there a reason for this inconsistency? Would you accept a PR updating Result to work like Option?

**Comment by pbiggar** [comment]
I noticed this myself the other day. Yes, fix would be welcome, thanks!
