### ISSUE TITLE
Upstream from Dark repo

### ISSUE THREAD

**Issue by pbiggar** [darklang/tablecloth#122]
Making a note of the functions we've written in the darklang repo that I haven't upstreamed yet:

Here's the bucklescript functions:

```
module Array = struct
  let iter ~(f : 'a -> unit) (arr : 'a array) : unit = Belt.Array.forEach arr f
end

module Option = struct
  let exec ~(f : 'a -> unit) (v : 'a option) : unit =
    match v with Some v -> f v | None -> ()

  let orLazy (v : 'a option) (v2 : unit -> 'a option) : 'a option =
    match v with Some v -> Some v | None -> v2 ()

  let orElseLazy (v : unit -> 'a option) (v2 : 'a option) : 'a option =
    match v2 with Some v2 -> Some v2 | None -> v ()

  let pair (a : 'a option) (b : 'b option) : ('a * 'b) option =
    match (a, b) with Some a, Some b -> Some (a, b) | _ -> None

  let map2 (a : 'a option) (b : 'b option) ~(f : 'a -> 'b -> 'c) : 'c option =
    match (a, b) with Some a, Some b -> Some (f a b) | _ -> None

  let andThen2 (a : 'a option) (b : 'b option) ~(f : 'a -> 'b -> 'c option) :
      'c option =
    match (a, b) with Some a, Some b -> f a b | _ -> None

  let isSomeEqualTo ~(value : 'a) (o : 'a option) : bool = Some value = o

  (* If a is some, then apply fn to a, return both a and the result.
    if either a or b is none, then return none
  *)
  let thenAlso (a : 'a option) ~(f : 'a -> 'b option) : ('a * 'b) option =
    let b = andThen ~f a in
    pair a b

  let withDefaultLazy (a : 'a option) ~(default : unit -> 'a) : 'a =
    match a with Some a -> a | None -> default ()
end

module Result = struct
  let isOk (v : ('err, 'ok) t) : bool = match v with Ok _ -> true | _ -> false
end

module List = struct
  (* From https://github.com/janestreet/base/blob/eaab227499b36bb90c2537bc6358a2d5caf75227/src/list.ml#L247 *)
  let findMap t ~f =
    let rec loop = function
      | [] ->
          None
      | x :: l ->
        (match f x with None -> loop l | Some _ as r -> r)
    in
    loop t


  let findWithIndex ~(f : int -> 'a -> bool) (l : 'a list) : int option =
    let rec findIndexHelper
        ~(i : int) ~(predicate : int -> 'a -> bool) (l : 'a list) : int option =
      match l with
      | [] ->
          None
      | x :: rest ->
          if predicate i x
          then Some i
          else findIndexHelper ~i:(i + 1) ~predicate rest
    in
    findIndexHelper ~i:0 ~predicate:f l

  let rec dropLeft ~(count : int) (l : 'a list) : 'a list =
    if count <= 0
    then l
    else
      match l with
      | [] ->
          []
      | [_] ->
          []
      | _ :: rest ->
          dropLeft ~count:(count - 1) rest

  let dropRight ~(count : int) (l : 'a list) : 'a list =
    l |> reverse |> dropLeft ~count |> reverse

  let range (start : int) (end_ : int) : 'a list =
    let length = end_ - start in
    if length < 0 then [] else Belt.List.makeBy length (fun i -> i + start)

  (* Takes everything before and after, but not including nexted element *)
  let splitOn ~(index : int) (l : 'a list) : 'a list * 'a list =
    (take ~count:index l, drop ~count:(index + 1) l)

  (* Moves item in oldPos into the position at newPos, pushing the element already at newPos down. Ex:
    l = [a b c d]
    moveInto 3 1 l, takes d and moves it between a & b. => [a d b c]
    NOTE: This is not swapping the elements in newPos & oldPos
  *)
  let moveInto ~(oldPos : int) ~(newPos : int) (l : 'a list) : 'a list =
    match getAt ~index:oldPos l with
    | Some value ->
        let index =
          (* Checks to see if we need to offset the newPos by -1, after removing the element at oldPos *)
          if newPos > oldPos
          then
            let len = List.length l in
            (* Clamp at list length to prevent overflow *)
            if newPos > len then len - 1 else newPos - 1
          else newPos
        in
        l |> removeAt ~index:oldPos |> insertAt ~index ~value
    | None ->
        l

  (* Partition into two lists, of potentially different type, using function
   * `f`.  Returns value in the first list for `Left` and second list for
   * `Right`. *)
  let partitionMap ~(f : 'c -> ('a, 'b) Either.t) (items : 'c list) :
      'a list * 'b list =
    Tablecloth.List.foldr
      ~init:([], [])
      ~f:(fun item (lefts, rights) ->
        match f item with
        | Left a ->
            (a :: lefts, rights)
        | Right b ->
            (lefts, b :: rights))
      items
end

module Float = struct
  let toString (f : float) : string = Js.Float.toString f
end

module Int = struct
  let toString (i : int) : string = Js.Int.toString i
end

module String = struct
  let splitAt ~(index : int) (s : string) : string * string =
    (slice ~from:0 ~to_:index s, slice ~from:index ~to_:(length s) s)

  let left ~(count : int) (s : string) : string = slice ~from:0 ~to_:count s

  let rec segment ~(size : int) (s : string) : string list =
    let front, back = splitAt ~index:size s in
    if back = "" then [front] else front :: segment ~size back

  let replaceChunk ~(from : int) ~(to_ : int) ~(replacement : string) s : string
      =
    slice ~from:0 ~to_:from s ^ replacement ^ slice ~from:to_ ~to_:(length s) s

  (* returns the index of the last occurrence of character c in string s before position i+1 or None if c does not occur in s before position i+1. *)
  let rindex_from_opt ~(pos : int) (s : string) (c : char) : int option =
    String.rindex_from_opt s pos c

  (* returns the index of the first occurrence of character c in string s after position i or None if c does not occur in s after position i.
 *)
  let index_from_opt ~(pos : int) (s : string) (c : char) : int option =
    String.index_from_opt s pos c
end

module StrDict = struct
  let values (dict : 'a t) : 'a list =
    Belt.Map.String.valuesToArray dict |> Array.toList

  let updateIfPresent ~(key : key) ~(f : 'v -> 'v) (dict : 'value t) : 'value t
      =
    update ~key ~f:(Option.map ~f) dict

  let mergeLeft (dict1 : 'v t) (dict2 : 'v t) : 'v t =
    Tablecloth.StrDict.merge
      ~f:(fun (_key : string) (v1 : 'v option) (v2 : 'v option) ->
        match (v1, v2) with Some _, _ -> v1 | None, _ -> v2)
      dict1
      dict2

  let mergeRight (dict1 : 'v t) (dict2 : 'v t) : 'v t =
    Tablecloth.StrDict.merge
      ~f:(fun (_key : string) (v1 : 'v option) (v2 : 'v option) ->
        match (v1, v2) with _, Some _ -> v2 | _, None -> v1)
      dict1
      dict2

  let count (dict : 'v t) = Belt.Map.String.size dict

  let mapValues (dict : 'v t) ~(f : 'v -> 'x) : 'x list =
    dict |> values |> List.map ~f

  let filterMapValues (dict : 'v t) ~(f : 'v -> 'x option) : 'x list =
    dict |> values |> List.filterMap ~f

  let mapWithKey (dict : 'v t) ~(f : key:string -> 'v -> 'x) : 'x t =
    Belt.Map.String.mapWithKey dict (fun key v -> f ~key v)

  let remove (dict : 'v t) ~(key : key) : 'v t = Belt.Map.String.remove dict key

  let removeMany (dict : 'v t) ~(keys : key list) : 'v t =
    Belt.Map.String.removeMany dict (Belt.List.toArray keys)

  let singleton ~(key : key) ~(value : 'v) : 'v t = empty |> insert ~key ~value

  let has ~key (dict : 'v t) : bool = Belt.Map.String.has dict key
end


module StrSet = struct
  let removeMany ~(values : string list) (set : t) : t =
    Belt.Set.String.removeMany set (Array.fromList values)

  let eq = Belt.Set.String.eq
end
```

**Comment by pbiggar** [comment]
And this is the list of functions we're written in native OCaml:

```
module Result = struct
  let or_ (ra : ('a, 'b) t) (rb : ('a, 'b) t) : ('a, 'b) t =
    match ra with Error _ -> rb | Ok _ -> ra

  let orElse (ra : ('a, 'b) t) (rb : ('a, 'b) t) : ('a, 'b) t =
    match rb with Error _ -> ra | Ok _ -> rb

  let orElseLazy (v : unit -> ('a, 'b) t) (v2 : ('a, 'b) t) : ('a, 'b) t =
    match v2 with Ok v2 -> Ok v2 | Error _ -> v ()

  let or_else = orElse
  let or_else_lazy = orElseLazy

  let and_ (ra : ('a, 'b) t) (rb : ('a, 'b) t) : ('a, 'b) t =
    match (ra, rb) with
    | Ok a, Ok _ ->
        Ok a
    | Ok _, Error b ->
        Error b
    | Error a, Ok _ ->
        Error a
    | Error a, Error _ ->
        Error a

  let map_error (f : 'err1 -> 'err2) (r : ('err1, 'ok) t) : ('err2, 'ok) t =
    Base.Result.map_error ~f r
end

module List = struct
  let findMap t ~f = Base.List.find_map t ~f
  let find_map = findMap
end

module Option = struct
  let exec ~(f : 'a -> unit) (v : 'a option) : unit =
    match v with Some v -> f v | None -> ()

  (* TODO: remove *)
  let valueExn (value : 'a option) : 'a =
    match value with Some v -> v | None -> raise Not_found

  let value_exn = valueExn

  let orLazy (v : 'a option) (v2 : unit -> 'a option) : 'a option =
    match v with Some v -> Some v | None -> v2 ()

  let or_else = orElse

  let orElseLazy (v : unit -> 'a option) (v2 : 'a option) : 'a option =
    match v2 with Some v2 -> Some v2 | None -> v ()

  let or_else_lazy = orElseLazy

  let pair (a : 'a option) (b : 'b option) : ('a * 'b) option =
    match (a, b) with Some a, Some b -> Some (a, b) | _ -> None

  let map2 (a : 'a option) (b : 'b option) ~(f : 'a -> 'b -> 'c) : 'c option =
    match (a, b) with Some a, Some b -> Some (f a b) | _ -> None

  let andThen2 (a : 'a option) (b : 'b option) ~(f : 'a -> 'b -> 'c option) :
      'c option =
    match (a, b) with Some a, Some b -> f a b | _ -> None

  let and_then2 = andThen2

  let isSomeEqualTo ~(value : 'a) (o : 'a option) : bool = Some value = o
  let is_some_equal_to = isSomeEqualTo

  (* If a is some, then apply fn to a, return both a and the result.
    if either a or b is none, then return none
  *)
  let thenAlso (a : 'a option) ~(f : 'a -> 'b option) : ('a * 'b) option =
    let b = andThen ~f a in
    pair a b

  let then_also = thenAlso
end

module StrDict = struct
  module XMap = Base.Map.M (Base.String)

  let iter ~(f : key -> 'value -> unit) (dict : 'value t) : unit =
    Base.Map.iteri ~f:(fun ~key ~data -> f key data) dict


  let to_list (dict : 'value t) : (key * 'value) list = Base.Map.to_alist dict

  let compare
      ~(f : 'value -> 'value -> int) (dict1 : 'value t) (dict2 : 'value t) =
    Base.Map.compare_direct f dict1 dict2

  let compare = Base.Map.compare_direct

  (* This is for when you believe there should never be duplicate
     * values, and want an exception to prove this invariant. *)
  let from_list_exn (l : (key * 'value) list) : 'value t =
    Base.Map.of_alist_exn (module Base.String) l

  let from_list_unique (l : (key * 'value) list) : (string, 'value t) Result.t =
    match Base.Map.of_alist (module Base.String) l with
    | `Duplicate_key k ->
        Result.fail ("Duplicate key: " ^ k)
    | `Ok dict ->
        Result.succeed dict

  let equal = Base.Map.equal
  let values = Base.Map.data
  let get ~(key : key) (dict : 'value t) = Base.Map.find dict key
  let filter l ~f = Base.Map.filter l ~f
  let insert ~(key : key) ~(value : 'value) (dict : 'value t) : 'value t =
    Base.Map.update dict key ~f:(fun _ -> value)

  let insert_no_override ~(key : key) ~(value : 'value) (dict : 'value t) :
      'value t =
    Base.Map.change dict key ~f:(fun old ->
        if old = None then Some value else old)

  let insert_fail_override ~(key : key) ~(value : 'value) (dict : 'value t) :
      [> `Duplicate | `Ok of 'value t] =
    Base.Map.add dict ~key ~data:value

  let singleton k v = from_list [(k, v)]

  let is_empty = Base.Map.is_empty

  let foldl
      ~(init : 'a) ~(f : key:key -> value:'value -> 'a -> 'a) (dict : 'value t)
      : 'a =
    Base.Map.fold ~init ~f:(fun ~key ~data -> f ~key ~value:data) dict

  let mapi ~(f : key:key -> value:'value -> 'a) (dict : 'value t) : 'value t =
    Base.Map.mapi ~f:(fun ~key ~data -> f ~key ~value:data) dict

  (** [size dict] returns the number of key-value pairs in [dict]. O(1) *)
  let size (dict : 'value t) : int =
    (* Base.Map.length is O(1) per https://ocaml.janestreet.com/ocaml-core/latest/doc/base/Base/Map/ *)
    Base.Map.length dict

  (** [contains_key dict ~key] returns whether the given [dict] contains [~key]. *)
  let contains_key (dict : 'value t) ~(key : string) : bool =
    Base.Map.mem dict key
end
```

**Comment by Dean177** [comment]
A lot of these have made their way into standard, though sometimes with slightly different names:

- Array
  - `iter` became `forEach`
- `Option`
  - `exec` became `forEach` 
  - `pair` became `both`
  - `map2` 
  - `valueExn` became `getUnsafe` (to match `get ~default`) 
  - `isSomeEqualTo` there is an `equal` function which is used like `Option.equal Int.equal (Some 5) None`
- Result
  - `isOk`
  - `or_`  
  - `and_` 
  - `mapError`
  - `pair` became `both`
  - `map2` 
- `List`
  - `findMap`
  - `findWithIndex` 
  - `dropLeft` | `Right`
  - `range`
  - `splitOn` became `splitAt` 
  - `moveInto` became `insertAt`
- `Float`
  - `toString`
- `Int`
  - `toString`
- `Dict`
  - `values`
  - `updateIfPresent` became a slightly more flexible `update`
  - `mapValues` & `mapWithKey` became `map`
  - `remove`
  - `singleton`
  - `has` became `includes`
  - `iter` became `forEach`
  - `toList`
  - `get`
  - `filter`
  - `insert`
  - `foldl` became `fold`
  - `mapi`
  - `size` became `length`
  - `isEmpty`
  - `contains_key` became `includes`

Of the functions remaining I think the following are no brainers for inclusion:

- Dict
  - `count` (since it _was_ added to Array & List)
  - `fromListUnique` 
  - `compare`
  - `equal`
  - `insert_no_override` / `insert_fail_override` although as one function which returns a `Result`
  - `filterMapValues` as `filterMap`

- String
  - splitAt 
  - left | right but maybe as `takeLeft` and `takeRight`?
  - replaceChunk but maybe as `replace ~from ~to_ ~with`
  - segment (a similar function was added to Array and List named `chunksOf`, as well as the more general `sliding`)
- String
  - `index_from_opt` a similar function was added to Array and List named `findIndex`, but didn't support the addition of a starting position. It seems like it would be useful to have it as an optional argument for those functions

But I am not so sure about these:

- Dict
  - `fromListExn` seems like we can have just the one function which returns a result, then we can allow the user to throw if they want when unwrapping the result
  - `mergeLeft` | `Right` these seem like they don't add much over 
      ```let mergeLeft = merge ~f:(fun _key left right -> (Option.or_ left right))```
      ```let mergeRight = merge ~f:(fun _key left right -> (Option.or_ right  left))```

- Option
  - `andThen2` I have just used `|> Option.both |> Option.andThen`, but could be convinced since we have `map2` already.
  - `thenAlso` is this to avoid nesting functions or is there some other motivation? Do you have an example usage?
  - `orLazy`, `orElseLazy`, `withDefaultLazy`

- `Result`
  - `orElse` how do you use this?

- List
  - partitionMap seems pretty nifty but when would you use it?

- (`Result`|`Option`).(`orLazy`|`orElseLazy`) 
  Ocaml has a [Lazy](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Lazy.html) module that can be used in a couple of pretty convenient ways:
  1. the `lazy` keyword
  1. `Lazy.from_val`
  1. `Lazy.from_fun`
 Whats the motivation for these?

**Comment by pbiggar** [comment]
Cool, comments inline. If I don't comment on it then it seems fine.

> * `Option`
>   * `exec` became `forEach`

Odd name. I see it matching Array/List but still odd.

>   * `pair` became `both`

Slight preference for pair.

>   * `valueExn` became `getUnsafe` (to match `get ~default`)

I like it!

>   * `isSomeEqualTo` there is an `equal` function which is used like `Option.equal Int.equal (Some 5) None`

I definitely prefer `isSomeEqualTo` compared to the alternative.

> * `Dict`

>   * `updateIfPresent` became a slightly more flexible `update`

This was a deliberate addition, as update is a little harder to use. Though, once we have `insert` and `remove`, perhaps it's better to have `update` to handle the other options.

>   * `mapValues` & `mapWithKey` became `map`

mapvalues allows you to specify a function that just works on the values, rather than needing a function which takes two parameters.

>   * `has` became `includes`

I find `has` to be a more intuitive name. That said, I think neither is consistent with what we've done elsewhere so maybe that's what we should do.

>   * `mapi`

We have map which you said takes a key, so probably don't need `mapi`.

>   * `size` became `length`

I think `length` is not a correct name here: dictionaries don't have lengths (like lists and arrays), but they do have a size.


> But I am not so sure about these:
> 
> * `Dict`
>   
>   * `fromListExn` seems like we can have just the one function which returns a result, then we can allow the user to throw if they want when unwrapping the result
>   * `mergeLeft` | `Right` these seem like they don't add much over
>     `let mergeLeft = merge ~f:(fun _key left right -> (Option.or_ left right))`
>     `let mergeRight = merge ~f:(fun _key left right -> (Option.or_ right  left))`

I personally find `mergeLeft|Right` to be a lot easier to use than the alternative above. I'm not even sure I understand how that works. That said, the name leaves a lot to be desired, we could do better with `mergeKeepLeft` and `mergeKeepRight` or something like that (none of us can remember which it means to merge left).

> * `Option`
>   
>   * `andThen2` I have just used `|> Option.both |> Option.andThen`, but could be convinced since we have `map2` already.

Yeah, we've found this useful

>   * `thenAlso` is this to avoid nesting functions or is there some other motivation? Do you have an example usage?

This has turned out to be super useful. It's for when you're chaining operations , and you need to keep the value of this operation for later:

```
getHandler id
|> Option.thenAlso ~f:Handler.getAST
|> Option.map ~f:(fun handler ast -> ...)
```

>   * `orLazy`, `orElseLazy`, `withDefaultLazy`

Discussed below.

> * `Result`
>   
>   * `orElse` how do you use this?

`Result.or_ a b` chooses `a` if it's `Ok` and otherwise chooses `b`. `Result.orElse a b` chooses `b` if it's `Ok` and otherwise chooses `a`. Particularly useful in a pipe:

```
Ok "the value I want"
|> Result.orElse (Ok "a default value")
```

> * `List`
>   
>   * `partitionMap` seems pretty nifty but when would you use it?

You want to split a list into two lists, without having to iterate over both lists after partitioning (we had some big lists that had performance impact of iterating).

> * (`Result`|`Option`).(`orLazy`|`orElseLazy`)
>   Ocaml has a [Lazy](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Lazy.html) module that can be used in a couple of pretty convenient ways:
>   
>   1. the `lazy` keyword
>   2. `Lazy.from_val`
>   3. `Lazy.from_fun`
>      Whats the motivation for these?

So we ported these over from Elm which doesn't have a lazy type. The point is that you have to do something expensive to get a default, and you only want to do the computation if you have to. As I understand it, there isn't a nice way to do it without a `orLazy` version (even if that version uses the `lazy` type, which I think would be a better).

**Comment by Dean177** [comment]
> As I understand it, there isn't a nice way to do it without a orLazy version 

Depends on your threshold for nice but 
```ocaml
Option.orElseLazy optionalValue ~f:(fun () -> ...expression...)
```

would be equivalent to 

```ocaml
Option.map(optionalValue, ~Lazy.from_val) 
|> Option.get ~default:(lazy ...expression...)
```

**Comment by pbiggar** [comment]
> I could totally see a getLazy : 'a option -> default:('a Lazy.t) -> 'a if you think its worth it though

Yeah, this would work for me

**Comment by Dean177** [comment]
Hopefully these now all exist as individual issues, my thinking is when we do the next release we try to get some additional contributors by pointing people to the ["good first issue"](https://github.com/darklang/tablecloth/labels/good%20first%20issue) and ["help wanted"](https://github.com/darklang/tablecloth/labels/help%20wanted) labels
