### ISSUE TITLE
MLI Link is broken

### ISSUE THREAD

**Issue by Discordius** [darklang/tablecloth#133]
Looks like sometime today (or yesterday evening) the MLI link on the readme was broken. It pointed to here: https://github.com/darklang/tablecloth/blob/master/bs/src/tablecloth.mli

It looks like the `bs` folder got renamed to `bucklescript`, which caused that path to change. Seems important to fix, since it's probably the first thing people try to access when they reach the repository. 

The new link should point here: https://github.com/darklang/tablecloth/blob/master/bucklescript/src/tablecloth.mli

**Comment by Dean177** [comment]
Thanks @Discordius
