### ISSUE TITLE
Deprecation warnings from bs-platform 7.3.2 for Js.Math.pow_int

### ISSUE THREAD

**Issue by Dean177** [darklang/tablecloth#141]
The `Js.Math.pow_int` function has been deprecated, we need an alternative implementation for  `Int.power ` and `Int.(**)`

**Comment by Dean177** [comment]
See the build failure here: https://circleci.com/gh/darklang/tablecloth/646?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by pbiggar** [comment]
I solved this in https://github.com/darklang/tablecloth/commit/31e6a07ccc2ea9f1481185a188843fc6054486ff, but it appears to have gotten lost somewhere in the copying.

**Comment by Dean177** [comment]
MDN [has this to say](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/pow): `If the base is negative and the exponent is not an integer, the result is NaN.`

And native throws `Invalid_argument "exponent can not be negative"`  so we can make the behaviour consistent.

My first PR was accidentally from my forked copy of the repo which was not in sync.

**Comment by pbiggar** [comment]
> And native throws Invalid_argument "exponent can not be negative" so we can make the behaviour consistent.

I think we should avoid throwing exceptions though.

**Comment by Dean177** [comment]
I think not throwing an exception here would actually make bugs harder to track down:
The bug originates some point earlier when you pass the negative number to power, but you either end up with a silent zero, or an exception if you then divide by the result.

**Comment by pbiggar** [comment]
I like the idea of this library not throwing exceptions, but cases like this I'm not actually sure what to do. Do you think we should generally throw for Invalid_arguments, or return a Result, or do default behaviour?

**Comment by Dean177** [comment]
I think numeric operations should get a safety pass here, if we make the functions total by returning options / results they will be very inconvenient to use, something like `1. /. squareRoot 2.` becomes `squareRoot 2. |> Option.andThen ~f:(fun rootTwo -> 1. /. rootTwo) |> Option.getUnsafe`.

I think its expected that these operations throw in Ocaml / Javascript, so users will be prepared for it

Things like `Result.attempt` allow users to run a batch of numeric operations and deal with any exceptions in one go too.

Elm makes some interesting choices here:
- Division by zero defaults two zero
- Its power function can return an Int or a Float, and its happy for the user to type the result as either

```elm
import Browser
import Html exposing (Html, button, div, text)

square : Int
square = (4 ^ 2)

float : Int
float = (4 ^ -2)

main = 
  div [] [
    Html.text "Division by zero:  ",
    String.fromInt (4 // 0) |> Html.text,
    Html.text "  Positive exponent:  ",
    square |> String.fromInt  |> Html.text,
    Html.text "  Negative exponent:  ",
    String.fromInt float |> Html.text
  ]
```
Produces `Division by zero: 0 Positive exponent: 16 Negative exponent: 0.0625`

**Comment by pbiggar** [comment]
OK, sounds good.

> And native throws Invalid_argument "exponent can not be negative" so we can make the behaviour consistent.

Agreed.

**Comment by pbiggar** [comment]
I think this is solved.
