### ISSUE TITLE
Feature Request: String.get, String.indexOf

### ISSUE THREAD

**Issue by lessp** [darklang/tablecloth#146]
Hey all, thanks for the hard work on Tablecloth (and Standard) and for deciding to merge the two together, I think it's the right move even though compromises like that can be very tough!

Would the two following operations make sense to add? No preference for naming.

`String.get` exists in `Standard` which is handy since the Stdlib-version throws.
`String.indexOf` exists in `Stdlib` as `index_opt`

EDIT: Semi-related and I realise this may be personal preference, but I also kind of miss utility-functions like `String.isEmpty(foo)` vs doing `foo == ""`

**Comment by Dean177** [comment]
Hey @lessp 

https://github.com/darklang/tablecloth/pull/131/files has been merged which includes `get`,  `getAt` and `isEmpty`. Once the merge has been finished there will be a new release.

A pull request for `indexOf`  would be very appreciated if you get the time

**Comment by lessp** [comment]
> Hey @lessp
> 
> https://github.com/darklang/tablecloth/pull/131/files has been merged which includes `get`, `getAt` and `isEmpty`. Once the merge of Standard has been finished (its pretty close) there will be a new release.
> 
> A pull request for `indexOf` would be very appreciated if you get the time

Awesome to hear! Will see what I can do! 👍
