### ISSUE TITLE
Add Result.orElse and Option.orElse

### ISSUE THREAD

**Issue by Dean177** [darklang/tablecloth#162]
These should work similarly to the corresponding `or_` functions but with the arguments swapped:

```ocaml
Ok "the value I want"
|> Result.orElse (Ok "a default value")
= Ok “the value I want”
```

**Comment by fabrizzioalco** [comment]
Hey, i want to take a look at this.

**Comment by fabrizzioalco** [comment]
Can you give me more context please

**Comment by Dean177** [comment]
Sure thing, I updated my original example to show the result.

Here is a bit more detail:

> Result.or_ a b chooses a if it's Ok and otherwise chooses b. Result.orElse a b chooses b if it's Ok and otherwise chooses a. Particularly useful in a pipe:
```ocaml 
Error "Snakes!"
|> Result.orElse (Ok "a default value")
= Ok “a default value”
```

Correct me if I am wrong here @pbiggar but the motivation for this function is to use `Result.or_` in a pipeline (`|>` )

**Comment by shubhamkumar13** [comment]
I had a question, does the Result module have an orElse function?

Because I couldn't find it in -> https://caml.inria.fr/pub/docs/manual-ocaml/libref/Result.html

**Comment by shubhamkumar13** [comment]
Found it in bucklescript directory

**Comment by shubhamkumar13** [comment]
Also there are 2 TableclothResult.ml one in native and one in bucklescript

**Comment by pbiggar** [comment]
> Also there are 2 TableclothResult.ml one in native and one in bucklescript

Yeah, those are two different packages. One is tablecloth-native on opam, the other is tablecloth-bucklescript on npm

**Comment by pm5** [comment]
There seems already a `Option.orElse` but not a `Result.orElse`.  Mind if I chip in?

**Comment by pbiggar** [comment]
Please do!
