### ISSUE TITLE
Native doesn't build with base v0.14.0

### ISSUE THREAD

**Issue by fabrizzioalco** [darklang/tablecloth#163]
Trying to tun the project show me this error: 
![Screen Shot 2020-06-21 at 1 21 12 PM](https://user-images.githubusercontent.com/25325755/85232520-f561a300-b3c4-11ea-98bb-76bc9edc4d2a.png)

So to run the project you should downgrade the base to v0.13.2 with this 
`opam pin add base v0.13.2`

This would downgrade the base and being able to run it

**Comment by Dean177** [comment]
Thanks @fabrizzioalco.

**Comment by pbiggar** [comment]
Fixed in #220
