### ISSUE TITLE
String.ofList does not exist

### ISSUE THREAD

**Issue by danielo515** [darklang/tablecloth#174]
This is on the usage page, first example:

```
open Tablecloth;
String.toList("Tablecloth")
->List.filterMap(~f=character => 
  Char.toCode(character)->Int.add(1)->Char.fromCode
)
->String.ofList
```

However, string ofList does not exist, the correct one is String.fromList (much more natural IMO)

**Comment by pbiggar** [comment]
Fixed in #227.

Thanks!
