### ISSUE TITLE
Add Or_error

### ISSUE THREAD

**Issue by ethanabrooks** [darklang/tablecloth#202]
I have a project that used Janestreet's [`Or_error`](https://ocaml.janestreet.com/ocaml-core/v0.13/doc/base/Base/Or_error/index.html). I would like to add that functionality to tablecloth. If there are objections we could probably fall back to `Result`.

This is my first time contributing to `tablecloth`. I'm also fairly new to the dev-ops side of OCaml so I may need a little guidance here and there.

**Comment by pbiggar** [comment]
Thanks! What's the reason for having both a Result and an Or_error? I remember reading a Jane St blog post about this, but I didn't really get the reasoning.

**Comment by ethanabrooks** [comment]
I think the best two alternatives are 
1. `('a, string) Result`. This is probably what we would go with, but once you put your error in a string, you basically take the error out of the type system, so your error handling has to remain pretty simple, e.g. just show the string for the first error that causes termination. This will not work well if you have a situation where an error arises while handling another error (the information from the first error will be lost).

2. `('a, exn) Result`. I don't pretend to fully understand the Janestreet logic for not doing this. I am somewhat new to OCaml and I haven't worked with `sexp`s very much. It sounds like this might work fine for smaller programs but runs into problems in the long run. If nothing else, it's a little verbose and unreadable. 
 
It also sounds like Janestreet wants to a establish a new standard for error handling, and I am kind of pressing the "I believe button" here.

**Comment by pbiggar** [comment]
It sounds like both approaches have some pros and some cons, so I think it would be better to stick to the simpler option (option 1), as the OrError approach isn't a common pattern in Rescript or F# (which is coming soon), or indeed outside the Jane St world AFAICT.

Thanks for the suggestions and explanation!

**Comment by ethanabrooks** [comment]
How about adding try/catch to your result module?

**Comment by pbiggar** [comment]
Yes, I think try/catch would be interesting. Can you post the signatures you're thinking of?

**Comment by ethanabrooks** [comment]
Hmm it seems like Tablecloth is emulating the conventions of the Rescript community. Looking through the Rescript `Belt.Result` API and [this blogpost](https://dev.to/kevanstannard/exploring-rescript-exception-handling-57o3) it looks like the idiomatic way to handle exceptions is with the built-in `try .... catch ...` syntax. Does that sound right to you?

**Comment by pbiggar** [comment]
I'm not really following what you mean? the blogpost doesn't talk about Result at all

**Comment by ethanabrooks** [comment]
Janestreet uses `Result.try_with` and `Or_error.try_with` but that doesn't seem to be the approach favored in the Rescript community.

**Comment by pbiggar** [comment]
Try_with seems like a good addition, thanks!
