### ISSUE TITLE
Website sidebar navigation

### ISSUE THREAD

**Issue by kate-grant** [darklang/tablecloth#262]
Scroll location not working for nested list items in Docs pages (ex. documentation/contributing#guiding-principles#over-communicate). May need to add regex to [Sidebar.js](https://github.com/darklang/tablecloth/blob/main/website/src/components/Sidebar.js) to remove parent-list anchor in nested list item url.

**Comment by Lomand** [comment]
I've fixed this bug with many other documentation related issues in the `next` branch.
