### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by pbiggar** [darklang/tablecloth#277]
Since both we and Rescript moved away from OCaml, we aren't seeing the same value in maintaining tablecloth, and we certainly haven't kept up with the work required to keep it relevant and useful.

I'd love to see someone take over the maintainership who has the time and inclination to take it in the right direction (see #214 for what I think that is)

If no-one is interested, it might be best to deprecate tablecloth.

If you're interested, feel free to reach out by email or in the Darklang slack, or just comment below.

**Comment by Lomand** [comment]
Hi Paul,
The last quarter of the year was a bit rough for me (currently undergoing a relocation, so zero to none time for open source), but once dust will settle I'll be glad to finish the transition to the `next` branch, as well as the `X.Mutate` submodules, as was originally planned. 

I use tablecloth regularly and really want this project to thrive.

**Comment by pm5** [comment]
I still see tablecloth as a very viable choice for an alternative standard library of OCaml.  Its API is much more consistent to me compared to Stdlib or Base, and much more modernistic with borrowed bits from Elm and maybe Rust.

I would love to take up the work of moving tablecloth forward on OCaml platform.

**Comment by pbiggar** [comment]
Thanks! Here's my current plan for moving forward:

- [ ] release current code as tablecloth-rescript
- [ ] merge `next` to `main`
- [ ] rewrite README to reflect current direction (see #214)
- [ ] split repo into 2 new repos: tablecloth-ocaml-base, tablecloth-rescript
- [ ] release onto opam and npm
- [ ] add fsharp repo, release onto nuget
- [ ] turn this repo into a "spec" - lists of functions/types and test cases that can be used from the other repos

**Comment by pm5** [comment]
Looks good to me.  The only thing I would add is at some point in the future we should move these repositories to a tablecloth GitHub organisation.

@pbiggar I suppose we can start picking up the work when we're splitting the repo?  Or do you think there are things in `next` that we can help wrap up?

**Comment by pbiggar** [comment]
Hmmm, tablecloth org is taken, but not by me. I wonder is it possible to contact the owner.

**Comment by pbiggar** [comment]
Looking through the codebase, splitting the repo has some unanswered questions, such as what do we do about the website. So maybe let's work on switching to the new plan from #214 and go from there.

**Comment by pbiggar** [comment]
I'm going to close this issue for now as it seems I'm still here. Let's move discussion into other issues, mostly #214.
