### ISSUE TITLE
Why is Option.foldrValues in the .mli file?

### ISSUE THREAD

**Issue by jdeisenberg** [darklang/tablecloth#31]
It looks as if `foldrValues` is a helper function for `values`. (What it really does is prepend an item to a list, so its name as a stand-alone function is not very meaningful.)

Suggestion: remove it from the `.mli` file, and nest the function in the `values` function in the `.ml` file. This would also allow you to get rid of `foldr_values`, which does not appear to be used anywhere else.

**Comment by pbiggar** [comment]
I was just looking at that. Agreed on both.

**Comment by jdeisenberg** [comment]
Want me to do that as part of the documentation process? (Also, I see a few functions with labeled parameters in the `.ml` file but not in the `.mli` file. Should that be part of a new PR or part of the documentation process as well?)

**Comment by pbiggar** [comment]
Yes please! New PRs are preferred - keeping them small makes them easier to review and easier to merge.

**Comment by j-m-hoffmann** [comment]
You can even inline it as an anonymous function. Using f last style it reads quite well

**Comment by pbiggar** [comment]
This was fixed.
