### ISSUE TITLE
Crashes VS-Code extension?

### ISSUE THREAD

**Issue by ntwilson** [darklang/tablecloth#36]
As soon as I install tablecloth-bucklescript (following the instructions in the README) to a project and open it in VS Code, the reason language server crashes and all the reason-specific IDE features disappear.  My logs say 
> Fatal error: exception Failure("Invalid subdirs entry")
Raised at file "stdlib.ml", line 33, characters 17-33
Called from file "src/analyze/FindFiles.re", line 49, characters 44-76
Called from file "list.ml", line 88, characters 20-23
Called from file "src/analyze/FindFiles.re", line 35, characters 30-69
Called from file "util/Infix.re", line 17, characters 68-73
Called from file "src/analyze/FindFiles.re", line 55, characters 2-51
Called from file "src/analyze/FindFiles.re", line 313, characters 19-70
Called from file "util/Infix.re" (inlined), line 16, characters 62-67
Called from file "src/analyze/FindFiles.re", line 303, characters 11-1023
Called from file "list.ml", line 88, characters 20-23
Called from file "src/analyze/FindFiles.re", line 300, characters 4-1023
Called from file "src/analyze/State.re", line 160, characters 55-129
Called from file "src/analyze/State.re", line 583, characters 24-73
Called from file "src/lsp/MessageHandlers.re" (inlined), line 15, characters 17-92
Called from file "src/lsp/MessageHandlers.re", line 296, characters 11-35
Called from file "src/lsp/BasicServer.re", line 44, characters 17-39
Called from file "src/lsp/BasicServer.re", line 111, characters 61-123
Called from file "src/lsp/Main.re", line 130, characters 6-255
Called from file "bin/Bin.re", line 3, characters 9-24
[Info  - 1:51:43 PM] Connection to server got closed. Server will restart.

It then restarts 4 times before giving up entirely.  

I'm using Windows 10, and VS-Code v.1.33.0 (user setup), the latest extension "reason-vscode" v. 1.5.2 (by Jared Forsyth).  And I'm writing my code in BuckleScript (OCaml syntax) not the Reason syntax.  

I have a minimal repro [here](https://github.com/ntwilson/tablecloth-vs-code-crash-repro).  If I do `npm install` and `npm run build`, and then open it in VS Code, the language server will crash.  If I remove "tablecloth-bucklescript" from bsconfig.json and reopen VS Code, it'll open fine with all IDE features working.

Any ideas where to start looking to get to the bottom of this?  I'm not even sure where to start.

**Comment by ntwilson** [comment]
Also, I get the same behavior if I clone the tablecloth repo, `npm install`, and open bs/src/tablecloth.ml

**Comment by ntwilson** [comment]
Oh, wow, I guess it's just because it doesn't like `"subdirs" : false` in the bsconfig.json file.  If I manually edit the bsconfig.json file to say `"subdirs" : true`, then everything works.  Looks like it's related to [this](https://github.com/jaredly/reason-language-server/issues/268) issue.

**Comment by pbiggar** [comment]
Thanks for the report!

I don't remember why I had it set like that. Do you think we can change it?

Otherwise, if we do need it, we'll probably have to rely on upstream fixing it.

**Comment by baransu** [comment]
@pbiggar I think this `"subdirs": false` is equal to just directory string so it's a possibility to fix it in the library itself not relying on RLS

**Comment by ntwilson** [comment]
Sounds like an upstream fix is coming very soon, so I doubt it makes sense to make changes here.

**Comment by pbiggar** [comment]
Cool. I'll close this for now so. Thanks for looking into it.
