### ISSUE TITLE
Consider adding `succeed` and `fail` constructors for Result

### ISSUE THREAD

**Issue by bkase** [darklang/tablecloth#39]
Right now, in order to construct a `Result`, you have to use the platform specific `Belt.Result.Ok` or Jane Street's `Result.return` and `Result.fail`.

Would you be open to a PR adding these functions (and likewise for Option)

**Comment by bkase** [comment]
Additionally, since `Belt` doesn't even have functions for the constructors you have to make a lambda in certain situations when you shouldn't.

Example: 

```ocaml
Array.initialize ~length:4 ~f:Result.succeed
(* vs *)
Array.initialize ~length:4 ~f:(fun x -> Belt.Result.Ok x)
```

This isn't an issue in Elm because Elm's type constructors can be used as functions.

**Comment by Dean177** [comment]
Good idea

**Comment by pbiggar** [comment]
👍
