### ISSUE TITLE
Opam install doesn't work

### ISSUE THREAD

**Issue by msvbg** [darklang/tablecloth#45]
This appears to be a known issue, but I'm creating an issue in this repository too so it doesn't get lost: https://github.com/ocaml/opam-repository/pull/13670#issuecomment-480545943.

**Comment by pbiggar** [comment]
Thanks for filing it. If anyone has any ideas for what could be going wrong, please let me know.

**Comment by pbiggar** [comment]
Working on releasing 0.0.6, held up on this bug. 

In opam it's at https://github.com/ocaml/opam-repository/pull/14052 (old bug was for 0.0.5).

**Comment by kit-ty-kate** [comment]
What version of dune do you have? It works perfectly in the CI: http://check.ocamllabs.io/?maintainers=Biggar

**Comment by kit-ty-kate** [comment]
And it installs perfectly locally on my laptop

**Comment by msvbg** [comment]
@kit-ty-kate Here's a repo which reproduces the issue: https://github.com/msvbg/opam_install_tcn_bug.

**Comment by kit-ty-kate** [comment]
ah, I see the problem..

**Comment by kit-ty-kate** [comment]
Should be fixed by #49

**Comment by kit-ty-kate** [comment]
For the opam files in the opam-repository I'll patch them tomorrow

**Comment by pbiggar** [comment]
@kit-ty-kate Great. Do I need to retag this new version as 0.0.6 again?

**Comment by kit-ty-kate** [comment]
mmh, no, otherwise it's going to break the opam package as the hash of the archive will change. It's easier to manually add the two `mv` before the `dune build` command in the build field in every versions of the package
