### ISSUE TITLE
Is there reason to drop Float.toString or Float.to_string?

### ISSUE THREAD

**Issue by kuy** [darklang/tablecloth#59]
I noticed Tablecloth API doesn't have `Float.toString` / `Float.to_string`. Both backends have corresponding APIs  [`Belt.Float.toString`](https://bucklescript.github.io/bucklescript/api/Belt.Float.html) and [`Base.Float.to_string`](https://ocaml.janestreet.com/ocaml-core/latest/doc/base/Base/Float/#val-to_string). I'll create PR for this if there is no reason to add this API. Please comment :)

**Comment by Dean177** [comment]
The issue is they behave differently in quite a few situations: https://github.com/darklang/tablecloth/pull/47#issuecomment-489460454

**Comment by kuy** [comment]
Thanks for a pointer. I need to tackle `toString` function which has "format" parameter with a default value (default format resolves a difference between both backends).

**Comment by Dean177** [comment]
An alternative would be just accepting the differences and making sure they are well documented.

**Comment by pbiggar** [comment]
I'd happily take a PR with the exact same behaviour (and test cases). I think if it doesn't have exactly the same behaviour, then it would be worse than simply requiring people to call the platform-specific function.

**Comment by kuy** [comment]
Thanks for comment. I'm working on this issue. Before do this, I needed to resolve [the precision problem](https://github.com/darklang/tablecloth/pull/60) on my dev env.

**Comment by Dean177** [comment]
Float.toString has returned, but is in need of documentation and testing
