### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by wpcarro** [darklang/tablecloth#67]
Is any documentation generated? Or is the recommendation to read the `.mli` files?

**Comment by Dean177** [comment]
The docs get generated from the mli files using [odoc](https://github.com/ocaml/odoc)

For the native side you can build and view from the repo by doing 
```sh
cd native
dune build @doc
open _build/default/_doc/_html/index.html
```

Or if you have done `opam install tablecloth-native` then you can use `odig` (`opam install odig`) to view the docs offline with `odig doc tablecloth-native`.

I haven't used odoc with Bucklescript, but apparently you can do so:
https://github.com/ocaml/odoc#using-odoc-with-bucklescriptreason

**Comment by wpcarro** [comment]
Thanks, @Dean177. Thoughts on supporting a `Makefile` with commands like `make docs` to generate the docs from this repo?

I'm happy to PR something if you're open to it.

**Comment by pbiggar** [comment]
@wpcarro Yes, that sounds great. It could nicely replace build.sh if you're up for a bit of scope creep :)

**Comment by wpcarro** [comment]
@pbiggar #68

**Comment by wpcarro** [comment]
Leaving [this link](https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/) as a future resource for either myself or someone else who'd like to add a `deploy-docs` step to the CircleCI config.

I may have a go at this over the weekend.
