### ISSUE TITLE
Add ocamlformat

### ISSUE THREAD

**Issue by pbiggar** [darklang/tablecloth#7]
We should ocamlformat using:

```
profile = sparse
break-string-literals = never
escape-strings = preserve
```

This would be a check in CI (once it's set up) to verify that everything is properly formatted.

**Comment by pbiggar** [comment]
This is getting serious. We should:

- ocamlformat every file
- check that ocamlformat works on CI

**Comment by wpcarro** [comment]
I don't mind giving this a go. I'll try and PR something today.

**Comment by Dean177** [comment]
@wpcarro I actually started this aaages ago: https://github.com/Dean177/tablecloth/tree/ocamlformat

But had trouble getting it working with the bucklescript side of things, that might be a good starting point. (Maybe just to check it works for the native side and submit that first)

**Comment by wpcarro** [comment]
@Dean177 thanks for chiming in. I'm testing out a configuration that I'm *hoping* should work here: #70. I'm expected the CI integration to fail at first, but I wanted to get something up to get some feedback.

Would love your review if you don't mind! Might not be worth looking at until I sort out the build issue. Should hopefully resolve that sooner than later.

**Comment by wpcarro** [comment]
Should we close this now because of #70 ?
