### ISSUE TITLE
Dedup test cases?

### ISSUE THREAD

**Issue by wpcarro** [darklang/tablecloth#71]
This is sort of a wishlist / half-baked idea. Is there a clever way for us to share the test cases between `bs` and `native`?

This may be over-engineered, but perhaps an S-expression DSL that could compile into test cases would be simple enough for us to seriously DRY up the testing code and ensure that our assertions are aligned between `bs` and `native`.

Or maybe there's a better way to design this that wouldn't involve writing a DSL compiler if it were just native OCaml.

Here's a sketch of a datastructure that I think could help dedup a lot of the assertions:

```
(List
  (init
    ("returns None for an empty list" [] None)
    ("returns an empty list for a single item list" ['a'] (Some []))
    ("returns all but the last item for a list with two or more items" ['a';'b';'c';'d'] ['a';'b';'c'])))
```

Like I said, this is half-baked, and I think an OCaml solution would be preferable. Just wanted to raise the issue before forgetting.

**Comment by Dean177** [comment]
I think you are suggesting a tablecloth-test library.

The differences between the bs-jest and [rely](https://www.npmjs.com/package/@reason-native/rely) are already pretty slim. 

Perhaps just porting from alcotest to rely?

**Comment by wpcarro** [comment]
@Dean177 I'm not too worried about the inconvenience of writing tests twice. It's more than duplicating the tests allows for the possibility of different levels of coverage between `bs` and `native`.

So unless there's a solution for fully de-duplicating the tests, I don't have much of an opinion.

I'll look into an OCaml solution and PR it just to illustrate what I have in mind.

**Comment by dmnd** [comment]
If the goal of tablecloth is to be able to write code that works in both native and js environments, it should be possible to write tests in terms of tablecloth and have those tests work in both environments too.

**Comment by Dean177** [comment]
We now have `AlcoJest` which means we can share the tests between implementations
