### ISSUE TITLE
`Array.get(~index=0, xs)` gets rewritten to `0[xs]`

### ISSUE THREAD

**Issue by dmnd** [darklang/tablecloth#72]
Possibly this is a Reason issue, not a Tablecloth one, but I'm too new to distinguish, so apologies:

```reason
open Tablecloth;
let x = Array.get(~index=0, xs);
```

gets rewritten by refmt to

```reason
open Tablecloth;
let x = 0[xs];
```

which is surprising to me at least. (I'm new to both Ocaml and Reason, so maybe I have different expectations.) Note that I originally wrote `xs[0]` but that's a type error...

Another related issue is that `0[xs]`, even if it is intended syntax, triggers a warning about omitted labels.

My workaround is to write

```reason
open Tablecloth;
let x = Tablecloth.Array.get(~index=0, xs);
```

**Comment by Dean177** [comment]
Its not a Reason issue, a similar issue happens in OCaml code too, we need to change Tablecloth a bit by changing `Array.get` to behave the way OCaml / Reason expects by:
- Dropping the named arguments
- Ensuring the argument order is the same as in the standard library

Then we could introduce `getAt` or `setAt` to preserve having functions we can use with named arguments.

**Comment by dmnd** [comment]
Done; take a look at #74

**Comment by pbiggar** [comment]
Some questions:

- Does OCaml overload the `[]` operator such that it `a[0]` actually calls tablecloth for `open Tablecloth;; Array.get arr 0`?

- What does Elm's API do?

**Comment by dmnd** [comment]
Looking at the output from Bucklescript at least, the operators used in the tests in #74 do get compiled to `Tablecloth.Array` calls. E.g.:

```ocaml
test "returns Some for an in-bounds index" (fun () -> 
  expect ([|"cat"; "dog"; "eel"|].(2)) |> toEqual (Some "eel"));
```

compiles to

```javascript
Jest.test("returns Some for an in-bounds index", (function (param) {
        return Jest.Expect[/* toEqual */12]("eel", Jest.Expect[/* expect */0](Curry._2(Tablecloth.$$Array[/* get */14], /* array */[
                            "cat",
                            "dog",
                            "eel"
                          ], 2)));
      }));
```


As for [Elm's API](https://package.elm-lang.org/packages/elm/core/latest/Array#get), it has the array parameter last, which I guess was the inspiration for Tablecloth's original `Array.get`:

```elm
get : Int -> Array a -> Maybe a
set : Int -> a -> Array a -> Array a
```

#74 changes them to array parameter first to work better with the pre-existing indexing operator above.

**Comment by pbiggar** [comment]
Thanks for the help here!
