### ISSUE TITLE
Fix CircleCI

### ISSUE THREAD

**Issue by pbiggar** [darklang/tablecloth#8]
I hooked up tablecloth to CircleCI, but I didn't make any effort to make it work.

There's two test scripts that could be run. It might be necessary to use `esy` or similar to have a repeatable install for opam packages.

**Comment by Dean177** [comment]
Hi @pbigger, I will pick this up.

Can you [enable GitHub status checks for this repo in circleci](https://circleci.com/blog/see-the-status-of-your-circleci-workflows-in-github/)?

**Comment by pbiggar** [comment]
Thanks!

I have checks turned on for the org already, and I can't see anything repo-specific. Is there something not working?

**Comment by Dean177** [comment]
I was expecting to see the status checks reported in pull-requests. Perhaps its something that needs to be configured on the GitHub side of things?

**Comment by pbiggar** [comment]
If I had to guess, the lack of a circleci config file is making it not add them?

**Comment by pbiggar** [comment]
Oh, I did only just enable CI on PRs, that's probably it.
