### ISSUE TITLE
overdue for a new release

### ISSUE THREAD

**Issue by martindemello** [darklang/tablecloth#93]
`npm install tablecloth-bucklescript` currently installs a version from over 100 commits ago - could you please make a new release?

(also if the project can be installed directly from github, could you add instructions to the readme?)

**Comment by pbiggar** [comment]
You're right, my apologies. I hope to take some time next week to release it.

**Comment by banacorn** [comment]
@pbiggar thank you, that would be great!

**Comment by banacorn** [comment]
Any progress?

**Comment by pbiggar** [comment]
@banacorn I've just released 0.0.7 to npm (https://www.npmjs.com/package/tablecloth-bucklescript). Working on releasing to opam.

**Comment by pbiggar** [comment]
Released to opam as well! (https://opam.ocaml.org/packages/tablecloth-native/)
