### ISSUE TITLE
String.to_list doesn't return a char list in bucklescript

### ISSUE THREAD

**Issue by martindemello** [darklang/tablecloth#94]
In the bucklescript code path, `String.to_list` produces a list of something that is not quite an ocaml `char`, so that `a |> String.to_list |> String.from_list` does not give back `a`, and attempting to do anything that expects an ocaml char with the contents of `String.to_list a` gives unpredictable results (mostly i seem to get a bunch of `0x0` unless i pass it straight back to a `Js` function).

**Comment by martindemello** [comment]
uncons does do the right thing, so this implementation works (not sure how efficiently, but it lets me map and filter the list with a function taking `char`, and works on unicode):

````
let explode s =
  let rec explode' s cs =
    match String.uncons s with
    | None -> List.reverse cs
    | Some (h, t) -> explode' t (h :: cs)
  in
  explode' s []
````

**Comment by pbiggar** [comment]
I've observed the same thing. My understanding was that chars are broken in bucklescript - am I wrong about that?

**Comment by martindemello** [comment]
you might well be right :) i've only used js-of-ocaml before this, thought i'd try out bucklescript for a small project and ran into this issue. but the uncons-based implementation does fix it.

**Comment by Dean177** [comment]
Actually let’s leave this open till we add a test case for it

**Comment by Dean177** [comment]
Ah, it was added [here](https://github.com/darklang/tablecloth/blob/1286045f4a38f41228b68be4e828c0d7e3a2ab4f/bucklescript/test/StringTest.re#L112)
